### ISSUE TITLE
Each child in a Renderer component list should have a unique "key" prop.

### ISSUE THREAD

**Issue by amars29** [GeekyAnts/react-pluggable#12]
## Subject
Whenever we are rendering the components using Renderer, let's say `<Renderer placement="top" />`, we are getting the warning as shown below:

<img width="525" alt="Screenshot 2020-11-23 at 5 31 33 PM" src="https://user-images.githubusercontent.com/73688673/99959872-d28f4c80-2db1-11eb-8c6c-13997b9efb55.png">

It will resolve if unique keys are provided to the list of components stored against each placeholder.

## Environment:
Version of react-pluggable: 0.4.2
Browser:  any [default: Chrome ]

## Expected behavior
The above console warning will get resolved.

**Comment by vipulbhj** [comment]
Maybe because of this.

Adding a `key` prop should do the trick

https://github.com/GeekyAnts/react-pluggable/blob/8c1df8f3ed889ceb8e356a9976b3d82487b2d503/src/plugins/RendererPlugin/components/Renderer.tsx#L36

**Comment by himanshu-satija** [comment]
Resolved [here](https://github.com/GeekyAnts/react-pluggable/pull/16)
